CREATE TABLE ALUNO (
	ID INT, 
	NOME VARCHAR(50),
	CURSO VARCHAR(30)
);

ALTER TABLE ALUNO ADD CONSTRAINT PK_ID PRIMARY KEY (ID);

ALTER TABLE ALUNO ADD COLUMN EMAIL VARCHAR(100);

ALTER TABLE ALUNO DROP COLUMN EMAIL;

DROP TABLE ALUNO;


CREATE TABLE ALUNO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50),
	CURSO VARCHAR(30)
);


CREATE TABLE FUNCIONARIO(
	ID INT,
	NOME VARCHAR(50),
	TELEFONE 	INT,
	EMAIL  TEXT,
	DATACONTRATACAO TIMESTAMP
	);

ALTER TABLE ALUNO DROP COLUMN CURSO;

ALTER TABLE ALUNO ADD COLUMN CURSO_ID INT;

CREATE TABLE CURSO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR (30)
);

ALTER TABLE ALUNO ADD CONSTRAINT FK_CURSO_ID FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID);

DROP TABLE ALUNO;

CREATE TABLE ALUNO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CURSO_ID INT NOT NULL REFERENCES CURSO(ID)
);

ALTER TABLE ALUNO ALTER COLUMN  NOME SET NOT NULL 
